### ISSUE TITLE
alice和bob的psi任务执行失败

### ISSUE THREAD

**Issue by liufan1029** [secretflow/kuscia#175]
部署方式：多机部署点对点集群（alice、  bob:）
alice作为发起方创建求交任务，执行失败
kubectl get kt secretflow-2023120414042034011337 -o yaml查看报错信息如下：
{
    "initiator": "alice",
    "job_id": "secretflow-202312041404203401133",
    "max_parallelism": 2,
    "tasks": [
        {
            "alias": "job-psi-secretflow-202312041404203401133",
            "app_image": "secretflow-image",
            "parties": [
                {
                    "domain_id": "bob"
                },
                {
                    "domain_id": "alice"
                }
            ],
            "priority": 100,
            "task_id": "secretflow-202312041404203401133",
            "task_input_config": "{\"sf_cluster_desc\":{\"devices\":[{\"name\":\"spu\",\"parties\":[\"bob\",\"alice\"],\"type\":\"spu\",\"config\":\"{\\\"runtime_config\\\":{\\\"protocol\\\":\\\"REF2K\\\",\\\"field\\\":\\\"FM64\\\"},\\\"link_desc\\\":{\\\"connect_retry_times\\\":60,\\\"connect_retry_interval_ms\\\":1000,\\\"brpc_channel_protocol\\\":\\\"http\\\",\\\"brpc_channel_connection_type\\\":\\\"pooled\\\",\\\"recv_timeout_ms\\\":1200000,\\\"http_timeout_ms\\\":1200000}}\"},{\"name\":\"heu\",\"parties\":[\"bob\",\"alice\"],\"type\":\"heu\",\"config\":\"{\\\"mode\\\": \\\"PHEU\\\", \\\"schema\\\": \\\"paillier\\\", \\\"key_size\\\": 2048}\"}],\"parties\":[\"bob\",\"alice\"]},\"sf_datasource_config\":{\"bob\":{\"id\":\"default-data-source\"},\"alice\":{\"id\":\"default-data-source\"}},\"sf_node_eval_param\":{\"inputs\":[{\"data_refs\":[{\"format\":\"csv\",\"party\":\"alice\",\"uri\":\"10alice.csv\"}],\"meta\":{\"schema\":{\"feature_types\":[\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\"],\"features\":[\"age\",\"balance\",\"campaign\",\"day\",\"default1\",\"duration\",\"education\",\"housing\",\"job_blue_collar\",\"job_entrepreneur\",\"job_housemaid\",\"job_management\",\"job_retired\",\"job_self_employed\",\"job_services\",\"job_student\",\"job_technician\",\"job_unemployed\",\"loan\",\"marital_divorced\",\"marital_married\",\"marital_single\",\"pdays\",\"previous\"],\"id_types\":[\"str\"],\"ids\":[\"id1\"]},\"@type\":\"type.googleapis.com/secretflow.component.IndividualTable\",\"num_lines\":\"-1\"},\"type\":\"sf.table.individual\"},{\"data_refs\":[{\"format\":\"csv\",\"party\":\"bob\",\"uri\":\"10bob.csv\"}],\"meta\":{\"schema\":{\"feature_types\":[\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\",\"str\"],\"features\":[\"contact_cellular\",\"contact_telephone\",\"contact_unknown\",\"month_apr\",\"month_aug\",\"month_dec\",\"month_feb\",\"month_jan\",\"month_jul\",\"month_jun\",\"month_mar\",\"month_may\",\"month_nov\",\"month_oct\",\"month_sep\",\"poutcome_failure\",\"poutcome_other\",\"poutcome_success\",\"poutcome_unknown\",\"y\"],\"id_types\":[\"str\"],\"ids\":[\"id2\"]},\"@type\":\"type.googleapis.com/secretflow.component.IndividualTable\",\"num_lines\":\"-1\"},\"type\":\"sf.table.individual\"}],\"domain\":\"preprocessing\",\"name\":\"psi\",\"attr_paths\":[\"input/receiver_input/key\",\"input/sender_input/key\",\"protocol\",\"precheck_input\",\"bucket_size\",\"curve_type\"],\"version\":\"0.0.1\",\"attrs\":[{\"ss\":[\"id1\"]},{\"ss\":[\"id2\"]},{\"s\":\"ECDH_PSI_2PC\"},{\"b\":true},{\"i64\":1048576},{\"s\":\"CURVE_FOURQ\"}]},\"sf_output_ids\":[\"psi-output\"],\"sf_output_uris\":[\"psi-out-secretflow-202312041404203401133.csv\"]}"
        }
    ]
}

**Comment by wsk95** [comment]
2023-12-04T14:16:09.526059435+08:00 stderr F WARNING:root:Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results.
2023-12-04T14:16:09.714806517+08:00 stderr F Traceback (most recent call last):
2023-12-04T14:16:09.714819769+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 395, in _CreateMessageFromTypeUrl
2023-12-04T14:16:09.714823882+08:00 stderr F     message_descriptor = pool.FindMessageTypeByName(type_name)
2023-12-04T14:16:09.714827351+08:00 stderr F KeyError: "Couldn't find message secretflow.component.IndividualTable"
2023-12-04T14:16:09.714830128+08:00 stderr F
2023-12-04T14:16:09.714832872+08:00 stderr F During handling of the above exception, another exception occurred:
2023-12-04T14:16:09.714835766+08:00 stderr F
2023-12-04T14:16:09.71485155+08:00 stderr F Traceback (most recent call last):
2023-12-04T14:16:09.714854524+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 580, in _ConvertFieldValuePair
2023-12-04T14:16:09.714857679+08:00 stderr F     self.ConvertMessage(value, sub_message)
2023-12-04T14:16:09.71486091+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 474, in ConvertMessage
2023-12-04T14:16:09.714879738+08:00 stderr F     methodcaller(_WKTJSONMETHODS[full_name][1], value, message)(self)
2023-12-04T14:16:09.714882976+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 605, in _ConvertAnyMessage
2023-12-04T14:16:09.714886094+08:00 stderr F     sub_message = _CreateMessageFromTypeUrl(type_url, self.descriptor_pool)
2023-12-04T14:16:09.714889245+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 397, in _CreateMessageFromTypeUrl
2023-12-04T14:16:09.714892756+08:00 stderr F     raise TypeError(
2023-12-04T14:16:09.714895992+08:00 stderr F TypeError: Can not find message descriptor by type_url: type.googleapis.com/secretflow.component.IndividualTable.
2023-12-04T14:16:09.714912041+08:00 stderr F
2023-12-04T14:16:09.714915185+08:00 stderr F During handling of the above exception, another exception occurred:
2023-12-04T14:16:09.714918004+08:00 stderr F
2023-12-04T14:16:09.714920966+08:00 stderr F Traceback (most recent call last):
2023-12-04T14:16:09.714923809+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 565, in _ConvertFieldValuePair
2023-12-04T14:16:09.714926728+08:00 stderr F     self.ConvertMessage(item, sub_message)
2023-12-04T14:16:09.714929848+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 476, in ConvertMessage
2023-12-04T14:16:09.714933015+08:00 stderr F     self._ConvertFieldValuePair(value, message)
2023-12-04T14:16:09.714936114+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 594, in _ConvertFieldValuePair
2023-12-04T14:16:09.71493938+08:00 stderr F     raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
2023-12-04T14:16:09.714942862+08:00 stderr F google.protobuf.json_format.ParseError: Failed to parse meta field: Can not find message descriptor by type_url: type.googleapis.com/secretflow.component.IndividualTable..
2023-12-04T14:16:09.714948475+08:00 stderr F
2023-12-04T14:16:09.714951528+08:00 stderr F During handling of the above exception, another exception occurred:
2023-12-04T14:16:09.71495433+08:00 stderr F
2023-12-04T14:16:09.714957496+08:00 stderr F Traceback (most recent call last):
2023-12-04T14:16:09.71496038+08:00 stderr F   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2023-12-04T14:16:09.714963688+08:00 stderr F     return _run_code(code, main_globals, None,
2023-12-04T14:16:09.714966676+08:00 stderr F   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
2023-12-04T14:16:09.714969952+08:00 stderr F     exec(code, run_globals)
2023-12-04T14:16:09.714972943+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py", line 345, in <module>
2023-12-04T14:16:09.714981807+08:00 stderr F     main()
2023-12-04T14:16:09.714985513+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
2023-12-04T14:16:09.714988863+08:00 stderr F     return self.main(*args, **kwargs)
2023-12-04T14:16:09.71499191+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
2023-12-04T14:16:09.714994895+08:00 stderr F     rv = self.invoke(ctx)
2023-12-04T14:16:09.714997922+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
2023-12-04T14:16:09.715001173+08:00 stderr F     return ctx.invoke(self.callback, **ctx.params)
2023-12-04T14:16:09.71500479+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
2023-12-04T14:16:09.715007805+08:00 stderr F     return __callback(*args, **kwargs)
2023-12-04T14:16:09.71501094+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py", line 304, in main
2023-12-04T14:16:09.715013975+08:00 stderr F     task_conf = KusciaTaskConfig.from_file(task_config_path)
2023-12-04T14:16:09.715017226+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/kuscia/task_config.py", line 127, in from_file
2023-12-04T14:16:09.715020426+08:00 stderr F     return cls.from_json(configs)
2023-12-04T14:16:09.715023579+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/secretflow/kuscia/task_config.py", line 59, in from_json
2023-12-04T14:16:09.715026767+08:00 stderr F     json_format.ParseDict(
2023-12-04T14:16:09.715029788+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 445, in ParseDict
2023-12-04T14:16:09.715033115+08:00 stderr F     parser.ConvertMessage(js_dict, message)
2023-12-04T14:16:09.715036288+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 476, in ConvertMessage
2023-12-04T14:16:09.715039508+08:00 stderr F     self._ConvertFieldValuePair(value, message)
2023-12-04T14:16:09.7150426+08:00 stderr F   File "/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py", line 588, in _ConvertFieldValuePair
2023-12-04T14:16:09.7150456+08:00 stderr F     raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
2023-12-04T14:16:09.715049188+08:00 stderr F google.protobuf.json_format.ParseError: Failed to parse inputs field: Failed to parse meta field: Can not find message descriptor by type_url: type.googleapis.com/secretflow.component.IndividualTable...

**Comment by wsk95** [comment]
@xiushuiguande 这是任务日志报的错

**Comment by wsk95** [comment]
apiVersion: kuscia.secretflow/v1alpha1
kind: KusciaTask
metadata:
  creationTimestamp: "2023-12-04T06:16:04Z"
  generation: 1
  labels:
    kuscia.secretflow/controller: kuscia-job
    kuscia.secretflow/interconn-protocol-type: kuscia
    kuscia.secretflow/job-id: secretflow-2023120414042034011337
    kuscia.secretflow/self-cluster-as-initiator: "true"
    kuscia.secretflow/task-alias: job-psi-secretflow-2023120414042034011337
  name: secretflow-2023120414042034011337
  ownerReferences:
  - apiVersion: kuscia.secretflow/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: KusciaJob
    name: secretflow-2023120414042034011337
    uid: ba185757-c84e-4f4f-ba98-e10bcc154e01
  resourceVersion: "37753"
  uid: ef0715c7-001d-4e91-ac35-d1a6df471a5c
spec:
  initiator: alice
  parties:
  - appImageRef: secretflow-image
    domainID: bob
    template:
      spec: {}
  - appImageRef: secretflow-image
    domainID: alice
    template:
      spec: {}
  scheduleConfig: {}
  taskInputConfig: '{"sf_cluster_desc":{"devices":[{"name":"spu","parties":["bob","alice"],"type":"spu","config":"{\"runtime_config\":{\"protocol\":\"REF2K\",\"field\":\"FM64\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"},{"name":"heu","parties":["bob","alice"],"type":"heu","config":"{\"mode\":
    \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"}],"parties":["bob","alice"]},"sf_datasource_config":{"bob":{"id":"default-data-source"},"alice":{"id":"default-data-source"}},"sf_node_eval_param":{"inputs":[{"data_refs":[{"format":"csv","party":"alice","uri":"10alice.csv"}],"meta":{"schema":{"feature_types":["str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str"],"features":["age","balance","campaign","day","default1","duration","education","housing","job_blue_collar","job_entrepreneur","job_housemaid","job_management","job_retired","job_self_employed","job_services","job_student","job_technician","job_unemployed","loan","marital_divorced","marital_married","marital_single","pdays","previous"],"id_types":["str"],"ids":["id1"]},"@type":"type.googleapis.com/secretflow.component.IndividualTable","num_lines":"-1"},"type":"sf.table.individual"},{"data_refs":[{"format":"csv","party":"bob","uri":"10bob.csv"}],"meta":{"schema":{"feature_types":["str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str","str"],"features":["contact_cellular","contact_telephone","contact_unknown","month_apr","month_aug","month_dec","month_feb","month_jan","month_jul","month_jun","month_mar","month_may","month_nov","month_oct","month_sep","poutcome_failure","poutcome_other","poutcome_success","poutcome_unknown","y"],"id_types":["str"],"ids":["id2"]},"num_lines":"-1"},"type":"sf.table.individual"}],"domain":"preprocessing","name":"psi","attr_paths":["input/receiver_input/key","input/sender_input/key","protocol","precheck_input","bucket_size","curve_type"],"version":"0.0.1","attrs":[{"ss":["id1"]},{"ss":["id2"]},{"s":"ECDH_PSI_2PC"},{"b":true},{"i64":1048576},{"s":"CURVE_FOURQ"}]},"sf_output_ids":["psi-output"],"sf_output_uris":["psi-out-secretflow-202312041404203401133.csv"]}'
status:
  completionTime: "2023-12-04T06:16:11Z"
  conditions:
  - lastTransitionTime: "2023-12-04T06:16:04Z"
    status: "True"
    type: ResourceCreated
  - lastTransitionTime: "2023-12-04T06:16:04Z"
    status: "True"
    type: Running
  - lastTransitionTime: "2023-12-04T06:16:11Z"
    status: "False"
    type: Success
  lastReconcileTime: "2023-12-04T06:16:11Z"
  message: The remaining non-failed parties counts 1 is less than the task success
    threshold 2
  partyTaskStatus:
  - domainID: bob
    message: Kuscia task failed
    phase: Failed
  - domainID: alice
    phase: Failed
  phase: Failed
  podStatuses:
    alice/secretflow-2023120414042034011337-0:
      createTime: "2023-12-04T06:16:04Z"
      namespace: alice
      nodeName: root-kuscia-autonomy-alice
      podName: secretflow-2023120414042034011337-0
      podPhase: Failed
      readyTime: "2023-12-04T06:16:08Z"
      reason: Error
      startTime: "2023-12-04T06:16:06Z"
      terminationLog: 'container[secretflow] terminated state reason "Error", message:
        "Table..\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback
        (most recent call last):\n  File \"/usr/local/lib/python3.8/runpy.py\", line
        194, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File
        \"/usr/local/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code,
        run_globals)\n  File \"/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py\",
        line 345, in <module>\n    main()\n  File \"/usr/local/lib/python3.8/site-packages/click/core.py\",
        line 1157, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/click/core.py\",
        line 1078, in main\n    rv = self.invoke(ctx)\n  File \"/usr/local/lib/python3.8/site-packages/click/core.py\",
        line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File
        \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 783, in invoke\n    return
        __callback(*args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/secretflow/kuscia/entry.py\",
        line 304, in main\n    task_conf = KusciaTaskConfig.from_file(task_config_path)\n  File
        \"/usr/local/lib/python3.8/site-packages/secretflow/kuscia/task_config.py\",
        line 127, in from_file\n    return cls.from_json(configs)\n  File \"/usr/local/lib/python3.8/site-packages/secretflow/kuscia/task_config.py\",
        line 59, in from_json\n    json_format.ParseDict(\n  File \"/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py\",
        line 445, in ParseDict\n    parser.ConvertMessage(js_dict, message)\n  File
        \"/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py\",
        line 476, in ConvertMessage\n    self._ConvertFieldValuePair(value, message)\n  File
        \"/usr/local/lib/python3.8/site-packages/google/protobuf/json_format.py\",
        line 588, in _ConvertFieldValuePair\n    raise ParseError(''Failed to parse
        {0} field: {1}.''.format(name, e))\ngoogle.protobuf.json_format.ParseError:
        Failed to parse inputs field: Failed to parse meta field: Can not find message
        descriptor by type_url: type.googleapis.com/secretflow.component.IndividualTable...\n"'
    bob/secretflow-2023120414042034011337-0:
      createTime: "2023-12-04T06:16:04Z"
      namespace: bob
      podName: secretflow-2023120414042034011337-0
      podPhase: Failed
      readyTime: "2023-12-04T06:16:07Z"
      startTime: "2023-12-04T06:16:06Z"
  serviceStatuses:
    alice/secretflow-2023120414042034011337-0-fed:
      createTime: "2023-12-04T06:16:04Z"
      namespace: alice
      readyTime: "2023-12-04T06:16:08Z"
      serviceName: secretflow-2023120414042034011337-0-fed
    alice/secretflow-2023120414042034011337-0-global:
      createTime: "2023-12-04T06:16:04Z"
      namespace: alice
      readyTime: "2023-12-04T06:16:08Z"
      serviceName: secretflow-2023120414042034011337-0-global
    alice/secretflow-2023120414042034011337-0-spu:
      createTime: "2023-12-04T06:16:04Z"
      namespace: alice
      readyTime: "2023-12-04T06:16:08Z"
      serviceName: secretflow-2023120414042034011337-0-spu
    bob/secretflow-2023120414042034011337-0-fed:
      createTime: "2023-12-04T06:16:04Z"
      namespace: bob
      readyTime: "2023-12-04T06:16:07Z"
      serviceName: secretflow-2023120414042034011337-0-fed
    bob/secretflow-2023120414042034011337-0-global:
      createTime: "2023-12-04T06:16:04Z"
      namespace: bob
      readyTime: "2023-12-04T06:16:07Z"
      serviceName: secretflow-2023120414042034011337-0-global
    bob/secretflow-2023120414042034011337-0-spu:
      createTime: "2023-12-04T06:16:04Z"
      namespace: bob
      readyTime: "2023-12-04T06:16:07Z"
      serviceName: secretflow-2023120414042034011337-0-spu
  startTime: "2023-12-04T06:16:04Z"

**Comment by cho-chem** [comment]
是的，现在需要提前创建 DomainData，使用 DomainDataID 来表示数据

**Comment by cho-chem** [comment]
抱歉给你带来不便了，这块主要是基于安全考虑的，之前的模式不需要数据授权，有越权的风险。
