### ISSUE TITLE
java调用kusica https接口问题，kusica中心部署的接口代码能调通，p2p部署的接口报错java.net.SocketException: Software caused connection abort: recv failed

### ISSUE THREAD

**Issue by zwj-edas** [secretflow/kuscia#441]
### Issue Type

Install/Deploy

### Search for existing issues similar to yours

Yes

### OS Platform and Distribution

centos7

### Kuscia Version

kuscia0.11.0b0

### Deployment

docker

### deployment Version

docker

### App Running type

secretflow

### App Running version

secreatflow1.7

### Configuration file used to run kuscia.

```shell
p2p和中心两种都部署成功，Postman能调通
```

### What happend and What you expected to happen.

```shell
同样的代码，在java调用https接口，访问中心部署的kuscia接口可以跑通，p2p部署的kuscia接口一直报错：java.net.SocketException: Software caused connection abort: recv failed
at java.net.SocketInputStream.socketRead0(Native Method)

请问是否有网络设置需要注意？
```

### Kuscia log output.

```shell
java.net.SocketException: Software caused connection abort: recv failed
at java.net.SocketInputStream.socketRead0(Native Method)
```

**Comment by wangzul** [comment]
目前只有P2P报错吗？你调用的是那个API。

**Comment by zwj-edas** [comment]
> 目前只有P2P报错吗？你调用的是那个API。

对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list

**Comment by wangzul** [comment]
> > 目前只有P2P报错吗？你调用的是那个API。
> 
> 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list

你的java代码发一下看看。

**Comment by zwj-edas** [comment]
> > > 目前只有P2P报错吗？你调用的是那个API。
> > 
> > 
> > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> 
> 你的java代码发一下看看。

https://github.com/secretflow/kuscia/issues/441#issuecomment-2413163805
代码是以上面链接里代码为模版写的，基本差不多

**Comment by zwj-edas** [comment]
> > > > 目前只有P2P报错吗？你调用的是那个API。
> > > 
> > > 
> > > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> > 
> > 
> > 你的java代码发一下看看。
> 
> https://blog.csdn.net/xiejunna/article/details/51726212 java代码是以这个为模版写的

p2p的接口总是这这里 urlCon.getOutputStream().write(xmlStr.getBytes("gbk"));  
报错：java.net.SocketException: Software caused connection abort: recv failed，
中心部署的接口正常返回结果

**Comment by 1139763082** [comment]
> > > > 目前只有P2P报错吗？你调用的是那个API。
> > > 
> > > 
> > > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> > 
> > 
> > 你的java代码发一下看看。
> 
> https://blog.csdn.net/xiejunna/article/details/51726212 java代码是以这个为模版写的

方便粘下源码么？

**Comment by zwj-edas** [comment]
> > > > > 目前只有P2P报错吗？你调用的是那个API。
> > > > 
> > > > 
> > > > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> > > 
> > > 
> > > 你的java代码发一下看看。
> > 
> > 
> > https://blog.csdn.net/xiejunna/article/details/51726212 java代码是以这个为模版写的
> 
> 方便粘下源码么？

源码没在外网，代码您可以之前看上面链接的代码，就是按照这个写的

**Comment by zwj-edas** [comment]
> > > > > 目前只有P2P报错吗？你调用的是那个API。
> > > > 
> > > > 
> > > > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> > > 
> > > 
> > > 你的java代码发一下看看。
> > 
> > 
> > https://blog.csdn.net/xiejunna/article/details/51726212 java代码是以这个为模版写的
> 
> 方便粘下源码么？

源码不是在外网写的，但是我就是按照链接：https://blog.csdn.net/xiejunna/article/details/51726212 java 里的例子写的，header里面加个token，证书存储在keystore证书库

**Comment by zwj-edas** [comment]
> > > > > 目前只有P2P报错吗？你调用的是那个API。
> > > > 
> > > > 
> > > > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> > > 
> > > 
> > > 你的java代码发一下看看。
> > 
> > 
> > https://blog.csdn.net/xiejunna/article/details/51726212 java代码是以这个为模版写的
> 
> 方便粘下源码么？

请问又遇到过此类问题么？postman能调通，但是java代码报错，查到说有可能是网络连接的问题，但是我检查防火墙端口都开放了，有没有可能是服务端连接关闭的太快呢？

**Comment by zwj-edas** [comment]
> > > > > 目前只有P2P报错吗？你调用的是那个API。
> > > > 
> > > > 
> > > > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> > > 
> > > 
> > > 你的java代码发一下看看。
> > 
> > 
> > https://blog.csdn.net/xiejunna/article/details/51726212 java代码是以这个为模版写的
> 
> 方便粘下源码么？

请问又遇到此类问题的吗？java代码报错，但是postman能调通，所以网络连接应该不是问题，有没有可能是服务端代码连接关闭太快？

**Comment by zwj-edas** [comment]
> > > > > 目前只有P2P报错吗？你调用的是那个API。
> > > > 
> > > > 
> > > > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> > > 
> > > 
> > > 你的java代码发一下看看。
> > 
> > 
> > https://blog.csdn.net/xiejunna/article/details/51726212 java代码是以这个为模版写的
> 
> 方便粘下源码么？

服务器关掉防火墙后，报错信息：javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
证书是没问题的，postman用的是同一个证书

**Comment by zimu-yuxi** [comment]
提供下部署kusica时，使用的通信协议，notls，tls还是mtls

**Comment by zwj-edas** [comment]
> 提供下部署kusica时，使用的通信协议，notls，tls还是mtls

这个是用的默认值，在哪里能查看呢

**Comment by zimu-yuxi** [comment]
> > 提供下部署kusica时，使用的通信协议，notls，tls还是mtls
> 
> 调用KusciaAPI 的映射接口访问的， “-k 参数传递的是节点容器 KusciaAPI 映射到主机的 MTLS 端口，保证和主机上现有的端口不冲突即可” 所以是MTLS吗？

这段说明是在哪里看的呢？

**Comment by zwj-edas** [comment]
> > > 提供下部署kusica时，使用的通信协议，notls，tls还是mtls
> > 
> > 
> > 调用KusciaAPI 的映射接口访问的， “-k 参数传递的是节点容器 KusciaAPI 映射到主机的 MTLS 端口，保证和主机上现有的端口不冲突即可” 所以是MTLS吗？
> 
> 这段说明是在哪里看的呢？

https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/Docker_deployment_kuscia/deploy_p2p_cn
docker多级部署点对点集群，部署alice节点这部分，“注意”上方

**Comment by zwj-edas** [comment]
> > > > > > > 目前只有P2P报错吗？你调用的是那个API。
> > > > > > 
> > > > > > 
> > > > > > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> > > > > 
> > > > > 
> > > > > 你的java代码发一下看看。
> > > > 
> > > > 
> > > > https://blog.csdn.net/xiejunna/article/details/51726212 java代码是以这个为模版写的
> > > 
> > > 
> > > 方便粘下源码么？
> > 
> > 
> > 服务器关掉防火墙后，报错信息：javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate 证书是没问题的，postman用的是同一个证书
> 
> 你再确认下ca证书，这个一般是证书不正确导致的，再次确认下是否和你postman使用的证书一致（postman调用正常说明kuscia服务没有问题）

我在这里测试，postman只需要选择kusciaapi-server.crt和kusciaapi-server.key，接口就可以调通；java代码里使用keystore存储证书，调用中心部署的master节点，8082-》18082端口可以正常访问；p2p部署的节点8082-》11081一直访问不通，即便把ca证书存入证书库

**Comment by zwj-edas** [comment]
> > > > > > > 目前只有P2P报错吗？你调用的是那个API。
> > > > > > 
> > > > > > 
> > > > > > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> > > > > 
> > > > > 
> > > > > 你的java代码发一下看看。
> > > > 
> > > > 
> > > > https://blog.csdn.net/xiejunna/article/details/51726212 java代码是以这个为模版写的
> > > 
> > > 
> > > 方便粘下源码么？
> > 
> > 
> > 服务器关掉防火墙后，报错信息：javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate 证书是没问题的，postman用的是同一个证书
> 
> 你再确认下ca证书，这个一般是证书不正确导致的，再次确认下是否和你postman使用的证书一致（postman调用正常说明kuscia服务没有问题）

我试过，证书不正确的话报的是另外一种错:sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath

**Comment by zwj-edas** [comment]
> > > > > > > 目前只有P2P报错吗？你调用的是那个API。
> > > > > > 
> > > > > > 
> > > > > > 对，p2p节点的报错，中心master的api没问题，好多接口都试过，一样的结果，/api/v1/domaindatasource/list
> > > > > 
> > > > > 
> > > > > 你的java代码发一下看看。
> > > > 
> > > > 
> > > > https://blog.csdn.net/xiejunna/article/details/51726212 java代码是以这个为模版写的
> > > 
> > > 
> > > 方便粘下源码么？
> > 
> > 
> > 服务器关掉防火墙后，报错信息：javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate 证书是没问题的，postman用的是同一个证书
> 
> 你再确认下ca证书，这个一般是证书不正确导致的，再次确认下是否和你postman使用的证书一致（postman调用正常说明kuscia服务没有问题）

你们有用java调用过的示例么

**Comment by zimu-yuxi** [comment]
可以参考secretpad代码
